"use client";

import { useEffect, useState } from "react";
import { formatSpeed, getQuestions, type Question } from "@/lib/questions";

const ROUND_SIZE = 5;
type Choice = "left" | "right";

function VehicleCard({ vehicle, side, onChoose, disabled, chosen, correct }: { vehicle: Question["left"]; side: Choice; onChoose: () => void; disabled: boolean; chosen: boolean; correct: boolean | null }) {
  const state = correct === null ? "" : correct ? "border-emerald-400 bg-emerald-50" : chosen ? "border-rose-400 bg-rose-50" : "opacity-60";
  return <button type="button" aria-label={`${vehicle.name}を選ぶ`} onClick={onChoose} disabled={disabled} className={`group relative flex min-h-56 flex-1 flex-col items-center justify-center rounded-2xl border-2 border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-blue-400 hover:shadow-md focus:outline-none focus:ring-4 focus:ring-blue-100 disabled:cursor-default ${state}`}>
    <span className="absolute left-4 top-3 text-xs font-bold uppercase tracking-widest text-slate-400">{side === "left" ? "A" : "B"}</span><span aria-hidden className="text-7xl transition group-hover:scale-110">{vehicle.emoji}</span><span className="mt-3 text-lg font-bold text-slate-800">{vehicle.name}</span>{correct !== null && <span className="mt-1 text-sm font-semibold text-slate-500">{formatSpeed(vehicle.speed)}</span>}
  </button>;
}

export function SpeedQuiz() {
  const [round, setRound] = useState(0); const [questionIndex, setQuestionIndex] = useState(0); const [score, setScore] = useState(0); const [selected, setSelected] = useState<Choice | null>(null); const [finished, setFinished] = useState(false); const [started, setStarted] = useState(false);
  const current = getQuestions(round * ROUND_SIZE, ROUND_SIZE)[questionIndex];
  const choose = (choice: Choice) => { if (selected || !current) return; setSelected(choice); if (current[choice].speed > current[choice === "left" ? "right" : "left"].speed) setScore((value) => value + 1); };
  const next = () => { if (questionIndex < ROUND_SIZE - 1) { setQuestionIndex((value) => value + 1); setSelected(null); } else setFinished(true); };
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (!started) return; if (event.key.toLowerCase() === "a") choose("left"); if (event.key.toLowerCase() === "b") choose("right"); if (event.key === "Enter" && selected) next(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); });
  const restart = () => { setRound((value) => (value + 1) % 6); setQuestionIndex(0); setScore(0); setSelected(null); setFinished(false); };
  if (!started) return <main className="grid min-h-screen place-items-center bg-[#f5f7fb] p-5"><section className="w-full max-w-md rounded-3xl bg-white p-8 text-center shadow-sm"><p className="text-7xl" aria-hidden>🚀</p><p className="mt-5 text-sm font-bold tracking-[.2em] text-blue-600">SPEED QUIZ</p><h1 className="mt-3 text-3xl font-black text-slate-900">どっちがはやい？</h1><p className="mt-5 leading-7 text-slate-600">2つの乗り物を見くらべて、<br />速いほうを選ぼう！</p><div className="mt-6 rounded-2xl bg-blue-50 p-4 text-left text-sm leading-6 text-blue-900"><p className="font-bold">あそびかた</p><p className="mt-1">全5問です。乗り物をタップして答えてね。</p></div><button type="button" onClick={() => setStarted(true)} className="mt-7 w-full rounded-xl bg-blue-600 px-5 py-3.5 font-bold text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-4 focus:ring-blue-100">ゲームをはじめる</button></section></main>;
  if (finished) return <main className="grid min-h-screen place-items-center bg-[#f5f7fb] p-5"><section className="w-full max-w-md rounded-3xl bg-white p-8 text-center shadow-sm"><p className="text-sm font-bold tracking-[.2em] text-blue-600">QUIZ CLEAR</p><h1 className="mt-3 text-3xl font-black text-slate-900">5問おわり！</h1><p className="mt-6 text-6xl font-black text-blue-600">{score}<span className="text-2xl text-slate-400"> / 5</span></p><p className="mt-3 text-slate-600">もう一度遊ぶと、別の5問に挑戦できます。</p><button type="button" onClick={restart} className="mt-8 w-full rounded-xl bg-blue-600 px-5 py-3 font-bold text-white hover:bg-blue-700">もう一度遊ぶ</button></section></main>;
  const isCorrect = selected ? current[selected].speed > current[selected === "left" ? "right" : "left"].speed : null;
  return <main className="min-h-screen bg-[#f5f7fb] px-5 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-3xl"><header className="flex items-start justify-between"><div><p className="text-sm font-bold tracking-[.2em] text-blue-600">SPEED QUIZ</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">どっちがはやい？</h1></div><div className="rounded-xl bg-white px-4 py-2 text-right shadow-sm"><p className="text-xs text-slate-500">スコア</p><p className="text-xl font-black text-blue-600">{score}<span className="text-sm text-slate-400"> / {questionIndex}</span></p></div></header><div className="mt-8 h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-blue-500 transition-all" style={{ width: `${(questionIndex / ROUND_SIZE) * 100}%` }} /></div><p className="mt-3 text-center text-sm font-semibold text-slate-500">全5問　・　{questionIndex + 1} / 5 問目</p><section className="mt-8 rounded-3xl bg-white p-5 shadow-sm sm:p-8"><h2 className="text-center text-xl font-bold">速いほうを選んでね</h2><div className="mt-6 flex flex-col gap-4 sm:flex-row"><VehicleCard vehicle={current.left} side="left" onChoose={() => choose("left")} disabled={Boolean(selected)} chosen={selected === "left"} correct={selected ? current.left.speed > current.right.speed : null} /><div className="grid place-items-center text-sm font-black text-slate-300">VS</div><VehicleCard vehicle={current.right} side="right" onChoose={() => choose("right")} disabled={Boolean(selected)} chosen={selected === "right"} correct={selected ? current.right.speed > current.left.speed : null} /></div>{selected && <div role="status" className={`mt-5 rounded-xl p-4 text-center font-bold ${isCorrect ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{isCorrect ? "せいかい！ はやいね！" : `おしい！ はやいのは ${current.left.speed > current.right.speed ? current.left.name : current.right.name}。`}<button type="button" onClick={next} className="mt-3 block w-full rounded-lg bg-slate-900 px-4 py-2 text-sm text-white hover:bg-slate-700">{questionIndex === 4 ? "結果を見る" : "次の問題へ"}</button></div>}</section><p className="mt-5 text-center text-xs text-slate-400">キーボードの A / B でも選べます</p></div></main>;
}
